### ISSUE TITLE
ptrace_memcpy have excess PEEKTEXT

### ISSUE THREAD

**Issue by screwer** [hyln9/VIKIROOT#1]
In case of write remainder. All data you have in 'src' array already. Just correct both ptrs and write whole word.

**Comment by hyln9** [comment]
If I'm correct, this won't work for initial n < sizeof(long).

**Comment by screwer** [comment]
Yes, you right. But in all other (most) cases PEEK not need.

**Comment by hyln9** [comment]
Agree.
