### ISSUE TITLE
unable to spawn remote shell

### ISSUE THREAD

**Issue by daemeonzane** [hyln9/VIKIROOT#14]
I'm using the LS991 (LG G4 US-Sprint variant) on MM. On localhost, I can at least get it to run, and wait for a remote shell. Using Termux on the device and nc to try to connect to the shell, I get nothing. Specifying an ip in my local subnet (192.168.254.x), to which the device is connected via wifi, the device completely reboots.
What am I doing wrong, or is this by design unable to function this way?

**Comment by hyln9** [comment]
Please read the Attention part.
Your device doesn't have a patched sepolicy likely.
