### ISSUE TITLE
Terminal connected, but multiple problems (Nougat)

### ISSUE THREAD

**Issue by PeregrineZ** [hyln9/VIKIROOT#8]
When I try your root method, I can get to the terminal on 7.0 Nougat using Termux, but root has not been achieved.

`whoami`
`u0_a211`

Also, when I run certain programs (such as mount), I get this error on the phone:

`CANNOT LINK EXECUTABLE "/system/bin/mount": cannot locate symbol "OpenSSL_add_all_algorithms" referenced by "/system/lib64/libselinux.so"...`

Is this a problem with the program, or that I'm on 7.0 (I'm running this on an AT&T S7)?

**Comment by hyln9** [comment]
Seems like my program had not even run once on your phone before `whoami`.
More details are needed, for example, the output of my program.
